### PR TITLE
Fix and improve side index generation.

### LINKED ISSUE #189: Index doesn't generate for pages in nested directories
Just the title, mentioned here: https://github.com/ros2/ros2_documentation/pull/409#issue-339637974

### PR DESCRIPTION
**Pull request by hidmic**
Closes #189. This pull request fixes broken side index generation for arbitrarily nested directories and improves rendering.

### CODE REVIEW

**Review by maryaB-osr — APPROVED** [review]
lgtm...? I'm probably not the best person to review this, but thank you!

File: _plugins/docs_generator.rb [hunk 1]
```diff
@@ -168,7 +171,7 @@ def build_with_sphinx(repo_name, repo_path, repo_data)
     end
 
     Dir.glob(File.join(output_path, "{_images/*.*,_downloads/**/*.*}"),
-             File::FNM_CASEFOLD).each do |static_file_path|
+             File::FNM_PATHNAME).each do |static_file_path|
```
Comment (nuclearsandwich) [inline _plugins/docs_generator.rb:176]: Was the casefold flag removed on purpose? I would have expected
`File::FNM_CASEFOLD | File::FNM_PATHNAME`.

File: _plugins/docs_generator.rb [hunk 2]
```diff
@@ -178,10 +181,10 @@ def build_with_sphinx(repo_name, repo_path, repo_data)
     repo_ignore_pattern = ["**/search.fjson", "**/searchindex.fjson", "**/genindex.fjson"]
     repo_ignore_pattern.push(*repo_data.fetch("ignore_pattern", []))
     Dir.glob(File.join(output_path, '**/*.fjson'),
-             File::FNM_CASEFOLD).each do |json_filepath|
+             File::FNM_PATHNAME).each do |json_filepath|
```
Comment (nuclearsandwich) [inline _plugins/docs_generator.rb:186]: Same as https://github.com/ros-infrastructure/rosindex/pull/195/files#diff-dac9c27c21ed6bc48485c0e6ed3dbb92R174

File: _plugins/docs_generator.rb [hunk 3]
```diff
@@ -64,6 +64,9 @@ def generate(site)
       documents = {}
       repo_build['documents'].each do |permalink, local_content|
         parent_path, * = permalink.rpartition('/')
+        while not parent_path.empty? and not documents.key? parent_path
+          parent_path, * = parent_path.rpartition('/')
```
Comment (nuclearsandwich) [inline _plugins/docs_generator.rb]: Minor nitpick but I think this is clearer when the tail isn't needed.
```suggestion
          parent_path = parent_path.rpartition('/').first
```

File: _plugins/docs_generator.rb [hunk 4]
```diff
@@ -64,6 +64,9 @@ def generate(site)
       documents = {}
       repo_build['documents'].each do |permalink, local_content|
         parent_path, * = permalink.rpartition('/')
+        while not parent_path.empty? and not documents.key? parent_path
```
Comment (nuclearsandwich) [inline _plugins/docs_generator.rb:69]: Does anything outside of this loop guarantee that parent pages are visited before child pages? Otherwise the parent may not be in `documents` yet?

File: _ruby_libs/pages.rb [hunk 5]
```diff
@@ -206,6 +207,9 @@ def initialize(site, parent_page, path, data)
 
   def add_child_page(page)
     self.data['child_pages'] << page
+    if page.data['indexed']
+      self.data['indexed_child_pages'] << page
```
Comment (nuclearsandwich) [inline _ruby_libs/pages.rb:211]: Are all child pages of indexed pages indexed or do you need to check that the child page is also indexed before adding it?

File: _plugins/docs_generator.rb (hunk 1 above)
Comment (hidmic) [reply _plugins/docs_generator.rb:176]: So, `File::FMN_CASEFOLD` was (and is) a bit unnecessary as I don't expect `File.join(output_path, "{_images,_downloads}")` to change case. It doesn't do any harm either though.

File: _plugins/docs_generator.rb (hunk 2 above)
Comment (hidmic) [reply _plugins/docs_generator.rb:186]: Same as above.

File: _plugins/docs_generator.rb (hunk 1 above)
Comment (nuclearsandwich) [reply _plugins/docs_generator.rb:176]: If it's not needed best not to confuse the issue :+1:

File: _ruby_libs/pages.rb (hunk 5 above)
Comment (hidmic) [reply _ruby_libs/pages.rb:211]: That's what `if page.data['indexed']` checks for (not the same as `self.data['indexed']`). Though an indexed child page of an un-indexed (parent) page won't show.

Not sure if we should `assert` or try propagate the child up to the closest ancestor that is indexed. We are doing neither.

File: _plugins/docs_generator.rb (hunk 4 above)
Comment (hidmic) [reply _plugins/docs_generator.rb:69]: Yes, that's the undocumented post-condition of [`DocPageGenerator::build_with_sphinx`](https://github.com/ros-infrastructure/rosindex/pull/195/files#diff-dac9c27c21ed6bc48485c0e6ed3dbb92R210-R233).

File: _plugins/docs_generator.rb (hunk 3 above)
Comment (hidmic) [reply _plugins/docs_generator.rb]: Neat! Suggestion accepted in 386f8b65f6a1fb6fd758cf0c5309cbf5b7a06c77 (to not mess with the DCO).

File: _ruby_libs/pages.rb (hunk 5 above)
Comment (nuclearsandwich) [reply _ruby_libs/pages.rb:211]: Sorry. No I misread the page.data check as self.data. Looks good.

File: _plugins/docs_generator.rb (hunk 4 above)
Comment (nuclearsandwich) [reply _plugins/docs_generator.rb:69]: Cool. I think a comment explaining as much would be helpful for people looking here in the future.

**Review by nuclearsandwich — APPROVED** [review]
Reviewed the logic and Ruby but haven't built it locally to verify that it resolves the issue.

File: _plugins/docs_generator.rb (hunk 4 above)
Comment (hidmic) [reply _plugins/docs_generator.rb:69]: Agreed. PTAL https://github.com/ros-infrastructure/rosindex/pull/195/commits/a95267f94a8ebd3e5b57c5801281661978a46806

Comment (nuclearsandwich) [reply _plugins/docs_generator.rb:69]: Looks good. Thanks.

**Comment by hidmic** [comment]
Alright, going in. Thank you both for the reviews!
