### PR TITLE
Fix sorting of repos and packages per distro

### LINKED ISSUE #96: Sort by last commit date not working?
Clicking on the button to sort packages by last commit date rearranges them in an order which doesn't look correct:

https://index.ros.org/packages/page/1/time/

sorttime

### PR DESCRIPTION
**Pull request by apojomovsky**
Closes https://github.com/ros-infrastructure/rosindex/issues/96
This PR:
- Fixes the sorting of both packages and repos by last commit date, as originally requested in the ticket
- Also fixes the sorting "by release" and "by documentation"

The sorting mechanism was using a single list across all the available distros, so the date shown in the date column corresponded the most recently modified version of a package whereas the sorting criteria was using the date from the commit date of the package released for a particular distro.

~~Pending:~~
~~- The sorting "by documentation" for packages is still not working.~~

To consider:
- I've found that this sorting mechanism is hardcoded to work only with recent distros, leading the packages/repos from older deprecated distros unsorted. Is this intended?

### CODE REVIEW

File: _plugins/rosindex_generator.rb [hunk 1]
```diff
@@ -468,6 +468,7 @@ def scrape_version(site, repo, distro, snapshot, vcs)
       'browse_uri' => get_browse_uri(repo.uri, repo.type, snapshot.version),
       # get the date of the last modification
       'last_commit_time' => vcs.get_last_commit_time(),
+
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky extra line?

File: _plugins/rosindex_generator.rb [hunk 2]
```diff
@@ -666,30 +673,38 @@ def generate_sorted_paginated(site, elements_sorted, default_sort_key, n_element
...
-      -(instances.default.snapshots.count {|d,s|
-        $recent_distros.include?(d) and s.released
+    repos_sorted['released'] = Hash.new
+    $all_distros.each do |distro|
+      repos_sorted['released'][distro] = repos_sorted['name'].reverse.sort_by { |name, instances|
+      -(instances.default.snapshots.count { |d,s|
+        $recent_distros.include?(d) and not s.released or not d == distro
       })
     }
+    end
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb:700]: @apojomovsky nit: something's weird with the indentation above.

File: _plugins/rosindex_generator.rb [hunk 3]
```diff
@@ -666,30 +673,38 @@ def generate_sorted_paginated(site, elements_sorted, default_sort_key, n_element
...
-        not $recent_distros.include?(d)
-      }.map { |d,s|
-        s.data['last_commit_time'].to_s
-      }.max
-    }.reverse
+    repos_sorted['time'] = Hash.new
+    $all_distros.each do |distro|
+      repos_sorted['time'][distro] = repos_sorted['name'].reverse.sort_by { |name, instances|
+        instances.default.snapshots.reject { |d,s|
+          s.nil? or not $recent_distros.include?(d) or not distro == d
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky consider `select`ing `instances.default.snapshots` based on distro instead for better readability.

File: _plugins/rosindex_generator.rb [hunk 4]
```diff
@@ -666,30 +673,38 @@ def generate_sorted_paginated(site, elements_sorted, default_sort_key, n_element
...
-    repos_sorted['doc'] = repos_sorted['name'].reverse.sort_by { |name, instances|
-      -(instances.default.snapshots.count { |d,s|
-        $recent_distros.include?(d) and not s.data['readme_rendered'].nil?
-      })
-    }
+    repos_sorted['doc'] = Hash.new
+    $all_distros.each do |distro|
+      repos_sorted['doc'][distro] = repos_sorted['name'].reverse.sort_by { |name, instances|
+        -(instances.default.snapshots.count { |d,s|
+          $recent_distros.include?(d) and not s.data['readmes'].nil? or not d == distro
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky hmm I'm under the impression this condition doesn't have the intended effect. It will count snapshots that do not belong to the distro of interest. Consider `select`ing snaphots instead.

File: _plugins/rosindex_generator.rb [hunk 5]
```diff
@@ -666,30 +673,38 @@ def generate_sorted_paginated(site, elements_sorted, default_sort_key, n_element
...
+    end
 
-    repos_sorted['released'] = repos_sorted['name'].reverse.sort_by { |name, instances|
-      -(instances.default.snapshots.count {|d,s|
-        $recent_distros.include?(d) and s.released
+    repos_sorted['released'] = Hash.new
+    $all_distros.each do |distro|
+      repos_sorted['released'][distro] = repos_sorted['name'].reverse.sort_by { |name, instances|
+      -(instances.default.snapshots.count { |d,s|
+        $recent_distros.include?(d) and not s.released or not d == distro
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky same as above.

File: _plugins/rosindex_generator.rb [hunk 6]
```diff
@@ -699,25 +714,34 @@ def sort_packages(site)
...
+          not s.nil? and $recent_distros.include?(d) and not s.data['readmes'].count > 0 or not distro == d
+        })
+      }.reverse
+    end
+
+    packages_sorted['released'] = Hash.new
+    $all_distros.each do |distro|
+      packages_sorted['released'][distro] = packages_sorted['name'].reverse.sort_by { |name, instances|
+        -(instances.snapshots.count { |d,s|
+          $recent_distros.include?(d) and not s.nil? and s.snapshot.released or not distro == d
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky same as for repo sorting here and immediately above.

File: _plugins/rosindex_generator.rb [hunk 7]
```diff
@@ -655,8 +656,14 @@ def generate_sorted_paginated(site, elements_sorted, default_sort_key, n_element
...
-        elements_sliced = elements.slice(p_start, elements_per_page)
-
+        unless sort_key == 'name' then
+          elements_sliced = Hash.new
+          elements.each do |distro, items|
+            elements_sliced[distro] = items.slice(p_start, elements_per_page)
+          end
+        else
+          elements_sliced = elements.slice(p_start, elements_per_page)
+        end
```
Comment (hidmic) [inline _plugins/rosindex_generator.rb]: @apojomovsky shouldn't `elements_sliced` always be a hash map of _things_ per distro?

**Review by hidmic — DISMISSED** [review]
@apojomovsky I left a few comments, thanks for addressing this!

**Comment by hidmic** [comment]
@chapulina mind to take a look?

**Comment by chapulina** [comment]
It would be helpful to have this deployed somewhere, otherwise it will take me a lot of time to build it locally. Any chance someone can deploy this with relative ease? @nuclearsandwich ? :pray:

**Comment by nuclearsandwich** [comment]
> It would be helpful to have this deployed somewhere, otherwise it will take me a lot of time to build it locally. Any chance someone can deploy this with relative ease? @nuclearsandwich ? pray

Building and deploying to rosindex.nuclearsandwich.com, will advise when it's up (or if the build fails.

**Comment by nuclearsandwich** [comment]
Live at http://rosindex.nuclearsandwich.com

**Review by chapulina — APPROVED** [review]

**Comment by hidmic** [comment]
Argh, forgot to squash merge. My bad!
